[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/config/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
depends = 'deoplete.nvim'
hook_source = 'source ~/.vim/config/plugins/deoplete_ternjs.rc.vim'
on_ft = ['javascript', 'coffee']

